"""create meetings and action_items tables

Revision ID: ee66e83a2b41
Revises: 
Create Date: 2026-10-08 20:20:17.085006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ee66e83a2b41'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('uploaded', 'transcribing', 'summarizing', 'done', 'failed', name='meetingstatus', native_enum=False, length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('transcript', mysql.LONGTEXT(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('key_topics', sa.JSON(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('action_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('assignee', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_items_meeting_id'), 'action_items', ['meeting_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Autogenerate also emitted drop_index for ix_action_items_meeting_id, but
    # MySQL refuses to drop an index that a foreign key needs (error 1553).
    # Dropping the table removes its indexes anyway.
    op.drop_table('action_items')
    op.drop_table('meetings')
